services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  dynamoSeeder:
    entrypoint: ["/bin/bash"]
    command: -c "aws dynamodb create-table --table-name users --attribute-definitions AttributeName=username,AttributeType=S --key-schema AttributeName=username,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD --endpoint-url http://dynamodb:8000"
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    links:
      - "dynamodb"
    environment:
      - AWS_ACCESS_KEY_ID=something
      - AWS_SECRET_ACCESS_KEY=something
      - AWS_REGION=us-east-1
  helloworld:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "dynamoSeeder"
    links:
      - "dynamodb"
    environment:
    - DYNAMODB_ENDPOINT=http://dynamodb:8000
