{{- if .Values.localDynamodb.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynamodb
    helm.sh/chart: {{ include "helloworld.chart" . }}
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - image: amazon/dynamodb-local
        name: dynamodb-local
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dynamodb
  name: dynamodb
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: dynamodb
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dynamodb-table-create
spec:
  activeDeadlineSeconds: 30
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: dynamodb-table-create
    spec:
    image: amazon/aws-cli
      - name: dynamodb-table-create
        image: amazon/aws-cli
        command: ["/bin/bash", "-c", "aws dynamodb create-table --table-name users --attribute-definitions AttributeName=username,AttributeType=S --key-schema AttributeName=username,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --table-class STANDARD --endpoint-url http://dynamodb:8000"]
      restartPolicy: Never
{{- end }}
